project:
  type: website
  title: "Procedural Knowledge Libraries"
  output-dir: docs

website:
  title: "Loaf"
  navbar:
    left:
      - href: pkl_outline.qmd
        text: Project Overview 
      - href: draftdviz.qmd 
        text: Data Viz Version Control Draft 
      - href: sci_indexing.qmd
        text: New Gen Research Indexing 
